import { expect, test } from '@playwright/test'

test('a rental sale before FIRE is marked at its actual sale age', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  const field = (label: string) => page.locator('label.field').filter({ hasText: label }).locator('input').first()
  await field('Current age').fill('50')
  await field('Target FIRE age').fill('52')
  await field('Life expectancy').fill('55')
  await page.getByRole('button', { name: '+ Investment property' }).click()
  const rental = page.locator('.property-card').first()
  const saleAge = rental.locator('label.field').filter({ hasText: 'Sell at age' }).locator('input')
  await saleAge.fill('50')
  await saleAge.blur()
  await expect(saleAge).toHaveValue('50')
  const chart = page.locator('.chart-card').filter({ has: page.getByRole('heading', { name: 'Account balances by age' }) })
  const saleLine = chart.locator('g.recharts-reference-line').filter({ hasText: 'Sale' })
  const fireLine = chart.locator('g.recharts-reference-line').filter({ hasText: 'FIRE' })
  await expect(saleLine).toBeVisible()
  const x = async (line: typeof saleLine) => Number(await line.locator('line').getAttribute('x1'))
  expect(await x(saleLine)).toBeLessThan(await x(fireLine))
})
