import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
})

test('professional clearing keeps unknown draft across modes and reload instead of writing zero', async ({ page }) => {
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  const savings = page.locator('label.field').filter({ hasText: 'Annual after-tax savings' }).locator('input')
  await savings.fill('24000')
  await savings.fill('')
  await savings.blur()
  await expect(savings).toHaveValue('')
  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  expect(persisted.inputs.annualSavings).toBe(24000)
  expect(persisted.draftByField.annualSavings).toBe('')
  expect(persisted.answerMeta.annualSavings.status).toBe('unknown')
  await page.getByRole('button', { name: 'Guided', exact: true }).click()
  await page.goto('/#/guided/saving/saving.amount')
  await expect(page.locator('[data-field="annualSavings"] input')).toHaveValue('')
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  await expect(savings).toHaveValue('')
  await page.reload()
  await expect(savings).toHaveValue('')
})

test('annual and monthly savings share one canonical amount across edits, modes, and refresh', async ({ page }) => {
  await page.goto('/#/guided/saving/saving.method')
  await page.getByRole('radio', { name: /monthly amount/ }).check()
  await page.goto('/#/guided/saving/saving.amount')
  const guidedSavings = page.locator('[data-field="annualSavings"] input')
  await guidedSavings.fill('2000')
  await expect(guidedSavings).toHaveValue('2,000')
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  const professionalSavings = page.locator('label.field').filter({ hasText: 'Annual after-tax savings' }).locator('input')
  await expect(professionalSavings).toHaveValue('24,000')
  await professionalSavings.fill('24000')
  await page.getByRole('button', { name: 'Guided', exact: true }).click()
  await expect(guidedSavings).toHaveValue('2,000')
  await page.reload()
  await expect(guidedSavings).toHaveValue('2,000')
  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  expect(persisted.inputs.annualSavings).toBe(24000)
  expect(persisted.answerMeta.annualSavings.status).toBe('confirmed')
})

test('invalid age and minus remain drafts; professional goal changes intent and revision once', async ({ page }) => {
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  const age = page.locator('label.field').filter({ hasText: 'Current age' }).locator('input')
  await age.fill('250')
  await age.blur()
  await expect(age).toHaveValue('250')
  let saved = await page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  expect(saved.inputs.currentAge).toBe(35)
  expect(saved.answerMeta.currentAge.status).toBe('unknown')
  await age.fill('36')
  await age.fill('abc')
  await age.blur()
  await expect(age).toHaveValue('abc')
  saved = await page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  expect(saved.draftByField.currentAge).toBe('abc')
  await age.fill('-')
  await age.blur()
  await expect(age).toHaveValue('-')
  saved = await page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  expect(saved.inputs.currentAge).toBe(36)
  const beforeRevision = saved.inputRevision
  await page.locator('label.field').filter({ hasText: 'Goal' }).locator('select').selectOption('dieWithZero')
  saved = await page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  expect(saved.inputRevision).toBe(beforeRevision + 1)
  expect(saved.resultRevision).toBeNull()
  expect(saved.planningIntent.spendingPreference).toBe('exploreCeiling')
  expect(saved.questionAnswers['intent.spending']).toBe('exploreCeiling')
})

test('switching modes never confirms an estimated amount just by viewing it', async ({ page }) => {
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  await page.evaluate(() => {
    const stored = JSON.parse(localStorage.getItem('fire-inputs')!)
    stored.state.answerMeta.annualSavings = { status: 'estimated', origin: 'default', updatedAt: new Date().toISOString(), assumptionValue: 40000 }
    localStorage.setItem('fire-inputs', JSON.stringify(stored))
  })
  await page.reload()
  const savings = page.locator('label.field').filter({ hasText: 'Annual after-tax savings' }).locator('xpath=following-sibling::small[1]')
  await expect(savings).toContainText('estimate')
  await page.getByRole('button', { name: 'Guided', exact: true }).click()
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  await expect(savings).toContainText('estimate')
  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  expect(persisted.answerMeta.annualSavings.status).toBe('estimated')
})

test('no-edit professional blur preserves estimate and revision; actual edits commit once', async ({ page }) => {
  test.setTimeout(60_000)
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  await page.evaluate(() => {
    const stored = JSON.parse(localStorage.getItem('fire-inputs')!)
    stored.state.answerMeta.annualSavings = { status: 'estimated', origin: 'default', updatedAt: new Date().toISOString(), assumptionValue: 40000 }
    localStorage.setItem('fire-inputs', JSON.stringify(stored))
  })
  await page.reload()
  const read = () => page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  const savings = page.locator('label.field').filter({ hasText: 'Annual after-tax savings' }).locator('input')
  await page.getByRole('button', { name: 'Run 1,000 simulations' }).click()
  await expect(page.locator('.mc-rate')).toBeVisible({ timeout: 45_000 })
  const before = await read()
  await savings.focus()
  await savings.blur()
  let after = await read()
  expect(after.inputRevision).toBe(before.inputRevision)
  expect(after.answerMeta.annualSavings).toEqual(before.answerMeta.annualSavings)
  await expect(page.locator('.mc-rate')).toBeVisible()
  await savings.fill('24000')
  await savings.blur()
  after = await read()
  expect(after.inputRevision).toBe(before.inputRevision + 1)
  expect(after.answerMeta.annualSavings.status).toBe('confirmed')
  const age = page.locator('label.field').filter({ hasText: 'Current age' }).locator('input')
  await age.fill('250')
  expect((await read()).inputRevision).toBe(after.inputRevision + 1)
  await age.blur()
  expect((await read()).inputRevision).toBe(after.inputRevision + 1)
})

test('guided monthly no-edit blur preserves exact annual amount and estimate', async ({ page }) => {
  await page.goto('/#/guided/saving/saving.method')
  await page.getByRole('radio', { name: /monthly amount/ }).check()
  await page.evaluate(() => {
    const stored = JSON.parse(localStorage.getItem('fire-inputs')!)
    stored.state.answerMeta.annualSavings = { status: 'estimated', origin: 'default', updatedAt: new Date().toISOString(), assumptionValue: 40000 }
    localStorage.setItem('fire-inputs', JSON.stringify(stored))
  })
  await page.reload()
  await page.goto('/#/guided/saving/saving.amount')
  const read = () => page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  const before = await read()
  const savings = page.locator('[data-field="annualSavings"] input')
  await savings.focus()
  await savings.blur()
  let after = await read()
  expect(after.inputs.annualSavings).toBe(40000)
  expect(after.inputRevision).toBe(before.inputRevision)
  expect(after.answerMeta.annualSavings).toEqual(before.answerMeta.annualSavings)
  await savings.fill('3333.33')
  await savings.blur()
  after = await read()
  expect(after.inputs.annualSavings).toBe(39999.96)
  expect(after.inputRevision).toBe(before.inputRevision + 1)
  await page.reload()
  expect((await read()).inputs.annualSavings).toBe(39999.96)
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  await page.getByRole('button', { name: 'Guided', exact: true }).click()
  expect((await read()).inputs.annualSavings).toBe(39999.96)
})

test('reset after professional goal edit resets guided intent to the default goal', async ({ page }) => {
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  await page.locator('label.field').filter({ hasText: 'Goal' }).locator('select').selectOption('dieWithZero')
  await page.getByRole('button', { name: 'Reset inputs' }).click()
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  expect(saved.inputs.goal).toBe('legacy')
  expect(saved.planningIntent.spendingPreference).toBe('undecided')
  await page.getByRole('button', { name: 'Guided', exact: true }).click()
  await page.goto('/#/guided/preferences/intent.spending')
  await expect(page.locator('input[name="intent.spending"][value="undecided"]')).toBeChecked()
})

test('clearing non-registry CPP and OAS preserves their legacy zero semantics', async ({ page }) => {
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  const read = () => page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  const cpp = page.locator('label.field').filter({ hasText: 'Estimated CPP/QPP per year at 65' }).locator('input').first()
  const before = await read()
  await cpp.fill('')
  await cpp.blur()
  let after = await read()
  expect(after.inputs.cppAnnualAt65).toBe(0)
  expect(after.inputRevision).toBe(before.inputRevision + 1)
  await expect(cpp).toHaveValue('0')
  const oas = page.locator('label.field').filter({ hasText: 'OAS per year at 65' }).locator('input').first()
  await oas.fill('')
  await oas.blur()
  after = await read()
  expect(after.inputs.oasAnnualAt65).toBe(0)
  expect(after.inputRevision).toBe(before.inputRevision + 2)
  await expect(oas).toHaveValue('0')
})

test('clearing non-registry FIRE asset target removes the canonical target', async ({ page }) => {
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  const target = page.locator('label.field').filter({ hasText: 'Target investable assets at FIRE' }).locator('input')
  await target.fill('1000000')
  const before = await page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  await target.fill('')
  await target.blur()
  const after = await page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  expect(after.inputs.fireTargetAssets).toBeNull()
  expect(after.canonical.targetAssets.status).toBe('unknown')
  expect(after.inputRevision).toBe(before.inputRevision + 1)
  await expect(target).toHaveValue('0')
})
