import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
})

test('professional clearing keeps unknown draft across modes and reload instead of writing zero', async ({ page }) => {
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  const savings = page.locator('label.field').filter({ hasText: 'Annual after-tax savings' }).locator('input')
  await savings.fill('24000')
  await savings.fill('')
  await savings.blur()
  await expect(savings).toHaveValue('')
  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  expect(persisted.inputs.annualSavings).toBe(24000)
  expect(persisted.draftByField.annualSavings).toBe('')
  expect(persisted.answerMeta.annualSavings.status).toBe('unknown')
  await page.getByRole('button', { name: 'Guided', exact: true }).click()
  await page.goto('/#/guided/saving/saving.amount')
  await expect(page.locator('[data-field="annualSavings"] input')).toHaveValue('')
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  await expect(savings).toHaveValue('')
  await page.reload()
  await expect(savings).toHaveValue('')
})

test('annual and monthly savings share one canonical amount across edits, modes, and refresh', async ({ page }) => {
  await page.goto('/#/guided/saving/saving.method')
  await page.getByRole('radio', { name: /monthly amount/ }).check()
  await page.goto('/#/guided/saving/saving.amount')
  const guidedSavings = page.locator('[data-field="annualSavings"] input')
  await guidedSavings.fill('2000')
  await expect(guidedSavings).toHaveValue('2,000')
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  const professionalSavings = page.locator('label.field').filter({ hasText: 'Annual after-tax savings' }).locator('input')
  await expect(professionalSavings).toHaveValue('24,000')
  await professionalSavings.fill('24000')
  await page.getByRole('button', { name: 'Guided', exact: true }).click()
  await expect(guidedSavings).toHaveValue('2,000')
  await page.reload()
  await expect(guidedSavings).toHaveValue('2,000')
  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  expect(persisted.inputs.annualSavings).toBe(24000)
  expect(persisted.answerMeta.annualSavings.status).toBe('confirmed')
})

test('invalid age and minus remain drafts; professional goal changes intent and revision once', async ({ page }) => {
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  const age = page.locator('label.field').filter({ hasText: 'Current age' }).locator('input')
  await age.fill('250')
  await age.blur()
  await expect(age).toHaveValue('250')
  let saved = await page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  expect(saved.inputs.currentAge).toBe(35)
  expect(saved.answerMeta.currentAge.status).toBe('unknown')
  await age.fill('36')
  await age.fill('abc')
  await age.blur()
  await expect(age).toHaveValue('abc')
  saved = await page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  expect(saved.draftByField.currentAge).toBe('abc')
  await age.fill('-')
  await age.blur()
  await expect(age).toHaveValue('-')
  saved = await page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  expect(saved.inputs.currentAge).toBe(36)
  const beforeRevision = saved.inputRevision
  await page.locator('label.field').filter({ hasText: 'Goal' }).locator('select').selectOption('dieWithZero')
  saved = await page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  expect(saved.inputRevision).toBe(beforeRevision + 1)
  expect(saved.resultRevision).toBeNull()
  expect(saved.planningIntent.spendingPreference).toBe('exploreCeiling')
  expect(saved.questionAnswers['intent.spending']).toBe('exploreCeiling')
})

test('switching modes never confirms an estimated amount just by viewing it', async ({ page }) => {
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  await page.evaluate(() => {
    const stored = JSON.parse(localStorage.getItem('fire-inputs')!)
    stored.state.answerMeta.annualSavings = { status: 'estimated', origin: 'default', updatedAt: new Date().toISOString(), assumptionValue: 40000 }
    localStorage.setItem('fire-inputs', JSON.stringify(stored))
  })
  await page.reload()
  const savings = page.locator('label.field').filter({ hasText: 'Annual after-tax savings' }).locator('xpath=following-sibling::small[1]')
  await expect(savings).toContainText('estimate')
  await page.getByRole('button', { name: 'Guided', exact: true }).click()
  await page.getByRole('button', { name: 'Professional', exact: true }).click()
  await expect(savings).toContainText('estimate')
  const persisted = await page.evaluate(() => JSON.parse(localStorage.getItem('fire-inputs')!).state)
  expect(persisted.answerMeta.annualSavings.status).toBe('estimated')
})
