export type GuidanceLanguage = 'en' | 'fr' | 'zh'
export type PageGuidance = { why: string; find: string; example: string }
type Copy = [why: string, find: string, example: string]

const en: Record<string, Copy> = {
  'family.people': ['Household size changes taxes, benefits and which incomes the plan includes.', 'Choose based on whose retirement finances you want to model; no document is needed.', 'Alex includes a partner because both people will rely on the same retirement plan.'],
  'family.ages': ['Current ages set the saving period and align each person’s future benefits.', 'Use dates of birth; enter ages today, not ages at retirement.', 'Alex is 40 and their partner is 38.'],
  'family.children': ['Children under 18 may add Canada Child Benefit income during early retirement.', 'Use each child’s current age; do not include planned or adult children.', 'A 7-year-old is included; a 20-year-old is not.'],
  'family.province': ['Province determines the income-tax estimate and some benefit rules.', 'Use the province where you expect to be tax-resident in retirement.', 'Someone retiring in Vancouver selects BC even if they work in Alberta today.'],
  'time.work': ['This age determines how many years you save and when the portfolio starts funding life.', 'Choose the age full-time employment ends; benefit claim ages are asked separately.', 'Alex stops full-time work at 55 but starts CPP at 65.'],
  'time.horizon': ['A longer horizon tests whether the plan survives more retirement years.', 'Choose a prudent planning age from family longevity and health context; it is not a prediction.', 'Alex tests through age 95 to leave room for a long life.'],
  'saving.method': ['The unit only changes how you enter the amount; the plan stores one annual total.', 'Pick the unit that matches how you track savings or see deposits on statements.', '$2,000 monthly and $24,000 yearly describe the same saving rate.'],
  'saving.amount': ['New contributions grow the portfolio before retirement.', 'Add net deposits from the last 12 months; exclude market gains and transfers between your accounts.', '$2,000 of new deposits each month equals $24,000 per year.'],
  'work.after': ['Work income after leaving full-time work can reduce early portfolio withdrawals.', 'Include realistic paid work or business income, not hobbies without expected income.', 'Alex expects consulting income for several years after leaving their main job.'],
  'work.amount': ['The annual amount controls how much of early spending the portfolio must cover.', 'Use expected gross annual income before income tax and business expenses.', '$1,500 per month of consulting is entered as $18,000 per year.'],
  'work.period': ['Start and end ages define exactly which retirement years receive this income.', 'Use the first and last ages you reasonably expect to earn it.', 'Consulting from age 55 through 62 creates a seven-year bridge.'],
  'assets.identify': ['Account types matter because contributions, growth and withdrawals are taxed differently.', 'Read the account title on bank or brokerage statements; select wrappers, not funds or stocks.', 'An ETF inside a TFSA is selected as TFSA, not as a separate account type.'],
  'account.tfsa.balance': ['TFSA withdrawals are tax-free and can flexibly fund retirement spending.', 'Use the current market value across all TFSAs, not unused contribution room.', 'Two TFSAs worth $40,000 and $25,000 are entered as $65,000.'],
  'account.rrsp.balance': ['RRSP/RRIF withdrawals are taxable, so this balance affects future tax and withdrawal order.', 'Use the current market value across RRSPs; include spousal RRSPs only if this combined plan owns them.', 'RRSP statements totaling $180,000 are entered as one household balance.'],
  'account.nonReg.balance': ['Non-registered investments can create yearly taxable distributions and gains when sold.', 'Use current market value from taxable brokerage accounts; exclude chequing cash used for bills.', 'A taxable portfolio currently worth $90,000 is entered as $90,000.'],
  'assets.cost': ['Cost base separates original investment cost from the taxable capital gain.', 'Use the adjusted cost base from your broker or tax records, not the current value.', 'A $100,000 portfolio bought for $80,000 has an $80,000 cost base.'],
  'allocation.tfsa': ['The split determines which tax treatment each dollar of future new savings receives.', 'Use planned payroll deductions and automatic transfers; TFSA, RRSP and non-registered shares must total 100%.', 'TFSA 30% plus RRSP 50% leaves 20% for non-registered investments.'],
  'fhsa.details': ['FHSA money can support a qualifying home purchase and has annual contribution limits.', 'Use the current FHSA market value and planned annual deposits from account statements or transfers.', 'A $12,000 balance with $8,000 planned yearly contributions uses both fields.'],
  'fhsa.open': ['The opening date matters because an FHSA has a limited participation period.', 'Find the first FHSA opening date on the institution’s records; count completed years.', 'An account opened two years ago is entered as 2.'],
  'locked.balance': ['Locked retirement money adds to wealth but may be unavailable during an early-retirement bridge.', 'Use the current statement value for the LIRA or locked DC account.', 'A former-employer LIRA worth $85,000 is entered here, not in RRSP.'],
  'locked.access': ['Access age determines when locked money can begin funding spending; ownership affects a couple plan.', 'Check the pension transfer or LIRA statement and applicable jurisdiction rules.', 'A LIRA available at 55 remains unavailable if retirement starts at 50.'],
  'locked.contributions': ['Ongoing employee and employer deposits change how this account grows before retirement.', 'Use annual totals from payroll and the employer plan statement; keep employee deposits within total savings.', '$6,000 employee plus $6,000 employer contributions are entered separately.'],
  'home.situation': ['Renting, owning and planning a purchase create different assets and cash flows.', 'Choose the path that best describes the retirement plan, not only today’s address.', 'A renter planning to buy in five years selects “plan to buy.”'],
  'home.value': ['Home value affects net worth, but only a future sale releases money for spending.', 'Use a recent comparable sale or assessment; enter a sale age only if sale is genuinely planned.', 'An $800,000 home kept for life adds net worth but no sale proceeds.'],
  'home.mortgage': ['A mortgage adds payments and reduces the net proceeds if the home is sold.', 'Check whether a balance remains on the latest mortgage statement; do not enter it again as other debt.', 'A paid-off home selects no even if it once had a mortgage.'],
  'mortgage.balance': ['The outstanding principal reduces housing equity and must be repaid.', 'Use the principal balance on the latest statement, not the original loan amount.', 'A mortgage opened at $500,000 with $310,000 left is entered as $310,000.'],
  'mortgage.payment': ['Payment and remaining term determine the years when housing debt consumes cash.', 'Use the contractual payment converted to an annual total and the remaining amortization years.', '$2,000 monthly is $24,000 annually with, for example, 18 years remaining.'],
  'purchase.time': ['Purchase timing determines how long assets grow before the down payment is taken.', 'Choose the expected age at closing, based on a realistic purchase window.', 'Buying in five years at current age 40 means purchase age 45.'],
  'purchase.price': ['Price and down payment determine how much cash leaves investments and how large the loan is.', 'Use a target price range and available down payment; keep closing costs outside these two amounts.', 'An $800,000 home with $200,000 down implies $600,000 financed.'],
  'purchase.loan': ['Payment and term determine whether the planned mortgage can be repaid and its future cash burden.', 'Use a lender quote or mortgage calculator; convert monthly payments to an annual amount.', '$3,500 monthly becomes $42,000 annually over the chosen amortization.'],
  'housing.other': ['Rental properties and other loans can materially change both income and required spending.', 'Include only items not already entered as the principal residence mortgage.', 'A rental mortgage belongs with the rental; a car loan belongs under other loans.'],
  'rental.0.value': ['Market value and cost base determine equity and the taxable gain when the rental is sold.', 'Use a recent valuation and adjusted cost base from purchase and improvement records.', 'A rental worth $600,000 with a $420,000 cost base has a $180,000 unrealized gain.'],
  'rental.0.income': ['Net rent adds taxable income while the property is held; a sale ends that income.', 'Use annual rent after operating costs but before mortgage payments; add a sale age only if planned.', '$30,000 rent minus $10,000 operating costs gives $20,000 net rent.'],
  'rental.0.mortgage': ['A linked mortgage reduces sale proceeds and its payments affect rental cash flow.', 'Use the rental’s own loan statement and do not duplicate it under other debts.', 'Select yes only for debt secured against this rental property.'],
  'rental.0.loan': ['Balance and payment determine rental equity and the loan’s yearly cash requirement.', 'Use the latest principal balance and annualized contractual payment.', '$1,500 monthly is entered as an $18,000 annual payment.'],
  'rental.0.term': ['Remaining years determine when the rental loan stops consuming cash.', 'Use remaining amortization, not the original mortgage term.', 'A 25-year mortgage with 17 years left is entered as 17.'],
  'debt.0.type': ['Loan type labels the obligation and helps prevent entering a property mortgage twice.', 'Use the loan agreement or statement to distinguish mortgage, vehicle loan or other debt.', 'A line of credit is entered as other debt.'],
  'debt.0.balance': ['Outstanding debt reduces net worth and may require payments during retirement.', 'Use today’s principal balance, excluding future interest.', 'A car loan with $14,000 principal left is entered as $14,000.'],
  'debt.0.payment': ['Payment and years remaining determine how long this loan adds to retirement spending.', 'Annualize the required payment and use the remaining term from the statement.', '$500 monthly for three more years becomes $6,000 annually for 3 years.'],
  'spending.method': ['You can enter a known total or build one from everyday categories; both lead to one annual budget.', 'Choose the path supported by your records and confidence, not the one that looks faster.', 'Someone with a detailed budget uses the total; someone unsure builds it by category.'],
  'spending.total': ['This after-tax lifestyle target drives the withdrawals the portfolio must provide.', 'Use today’s prices and exclude loan payments entered separately; annualize monthly spending.', '$4,000 monthly of lifestyle spending becomes $48,000 per year.'],
  'spending.homeFood': ['Housing upkeep and groceries are core recurring costs that continue after work ends.', 'Review recent annual spending; exclude mortgages or loans already entered elsewhere.', '$18,000 housing upkeep plus $9,000 groceries are entered separately.'],
  'spending.travelHealth': ['Travel and health costs often change in retirement and should be planned explicitly.', 'Use recent spending plus realistic insurance, dental, medication and trip plans.', '$6,000 travel and $3,000 health costs are annual amounts.'],
  'spending.utilitiesTransport': ['Utilities and transportation remain recurring even when commuting changes.', 'Review bills, vehicle costs and transit; adjust only changes you actually expect after work.', 'Lower commuting may reduce transport from $8,000 to $5,000 per year.'],
  'spending.funOther': ['Entertainment and uncategorized needs keep the budget from covering essentials only.', 'Use bank or card categories and include irregular annual items; avoid a vague oversized cushion.', '$4,000 entertainment plus $2,000 other costs completes the worksheet.'],
  'cpp.self': ['CPP/QPP amount and claim age determine when taxable government income begins.', 'Use the age-65 annual estimate from Service Canada or Retraite Québec; the helper is for users without it.', '$1,000 per month at 65 is a $12,000 annual age-65 estimate.'],
  'oas.self': ['OAS amount and start age determine later taxable income and possible clawback exposure.', 'Use the age-65 estimate or estimate from Canadian residence after age 18.', '$725 per month at 65 is entered as $8,700 per year.'],
  'cpp.partner': ['Your partner’s CPP/QPP is separate income with its own amount and claim age.', 'Use the partner’s own Service Canada or Retraite Québec estimate, not yours.', 'A partner expecting $9,600 annually at 65 enters that amount on this page.'],
  'oas.partner': ['Your partner’s OAS is calculated separately and may begin at a different age.', 'Use the partner’s residence history or official estimate.', 'A partner claiming OAS at 67 enters the age-65 base amount and claim age 67.'],
  'pension.self': ['A lifetime pension is income; a DC/LIRA plan is an account balance and must not be entered the same way.', 'Check whether the statement promises a periodic benefit or shows only an invested balance.', 'A promised $2,500 monthly lifetime benefit is DB; a $200,000 balance is DC/LIRA.'],
  'pension.self.details': ['Annual pension and start age define the income bridge supplied by the employer plan.', 'Use the retirement estimate on the pension statement; annualize monthly payments.', '$2,500 monthly starting at 60 is $30,000 per year from age 60.'],
  'pension.self.indexing': ['Indexing protects purchasing power; a bridge is temporary income that usually ends near 65.', 'Read the plan booklet for CPI wording, indexing percentage and bridge amount.', 'A fully indexed pension rises with inflation; a $6,000 bridge is entered separately.'],
  'pension.partner': ['Your partner’s employer plan must also be classified as lifetime income or an account balance.', 'Use the partner’s pension statement and avoid combining it with your pension.', 'A partner’s locked DC balance belongs in the locked-account path, not as DB income.'],
  'pension.partner.details': ['The partner pension amount and start age determine when household withdrawals fall.', 'Use the partner’s own retirement estimate and annualize any monthly figure.', '$1,500 monthly from age 65 is $18,000 annual partner pension income.'],
  'pension.partner.indexing': ['Partner pension indexing and bridge terms affect household purchasing power over time.', 'Check the partner plan booklet for CPI adjustments and any temporary bridge.', 'A fixed pension selects no indexing even if the initial amount is high.'],
  'intent.legacy': ['This preference tells the results whether to emphasize remaining after-tax assets; it is not inferred from children.', 'Choose based on your own intent toward family, friends or causes; no financial statement is needed.', 'Someone without children may still want to leave assets to a charity.'],
  'intent.spending': ['Keeping the budget fixed and exploring a theoretical ceiling answer different planning questions.', 'Choose whether you want comparison only; viewing a ceiling does not change your entered budget.', 'Alex keeps $50,000 spending and separately views how much more may be possible.'],
  'intent.confirm': ['Confirmation prevents the calculator from silently translating a personal preference into a technical goal.', 'Read the summary and go back if it does not describe what you want compared.', '“Keep spending and compare what remains” maps to an estate comparison only after confirmation.'],
  'invest.mix': ['Investment mix determines expected return and year-to-year uncertainty.', 'Use the broad stock/bond/cash split across retirement investments, not a recent performance number.', 'A 60% stock and 40% bond portfolio selects Balanced 60/40.'],
  'invest.fees': ['Fees reduce returns every year; inflation connects today’s prices to future nominal dollars.', 'Find MERs on fund facts and advisory statements; use a long-run inflation assumption, not one recent year.', 'A 0.2% ETF fee and 2.1% inflation are entered as percentages.'],
  'invest.tax': ['Taxable distributions create annual tax drag before retirement; the marginal rate estimates that cost.', 'Use fund distribution history and the marginal rate from a recent tax return or calculator.', 'A broad ETF may distribute about 2% while a working marginal rate may be 35%.'],
  'invest.strategy': ['Withdrawal order changes tax, benefit clawbacks and the assets left later.', 'Choose the strategy you want to compare; the results section can show alternatives.', 'A bracket-capped RRSP meltdown uses low-income years without draining RRSP all at once.'],
  'assumptions.review': ['The projection should run only after you recognize the estimates it depends on.', 'Review return, volatility, fees, inflation and tax assumptions; change earlier pages if needed.', 'Accepting a 3% real return means testing that scenario, not promising it will occur.'],
}

const zh: Record<string, Copy> = {
  'family.people': ['家庭人数会改变税额、福利，以及计划需要纳入哪些收入。', '按“谁会共同依赖这份退休计划”选择，不需要查文件。', 'Alex和伴侣共用退休资金，所以选择夫妻合并。'],
  'family.ages': ['当前年龄决定剩余储蓄年数，并对齐每个人未来领取福利的时间。', '按出生日期填写今天的年龄，不要填退休时年龄。', 'Alex现在40岁，伴侣38岁。'],
  'family.children': ['未满18岁的孩子可能让提前退休阶段获得加拿大儿童福利。', '按孩子生日填写当前年龄；不要纳入计划中的孩子或成年子女。', '7岁孩子需要纳入，20岁子女不纳入。'],
  'family.province': ['省份决定所得税估算和部分福利规则。', '填写预计退休后成为税务居民的省份，不一定是现在工作的省份。', '现在在阿省工作、计划在温哥华退休的人选择BC。'],
  'time.work': ['停工年龄决定还能储蓄几年，以及投资从哪一年开始支付生活费。', '填写停止全职工作的年龄；CPP/OAS起领年龄会另问。', 'Alex在55岁停工，但65岁才开始领CPP。'],
  'time.horizon': ['规划终点越晚，系统测试的退休年数越长。', '结合家族寿命和健康状况选一个审慎年龄；这不是寿命预测。', 'Alex测试到95岁，为长寿留出余量。'],
  'saving.method': ['月/年只改变填写方式，系统最终都会保存为全年金额。', '选择最符合你记账方式或账单显示方式的单位。', '每月2,000和每年24,000代表同一储蓄速度。'],
  'saving.amount': ['真正新增的供款会在退休前持续积累。', '汇总过去12个月净存入；排除市场涨幅和自己账户之间的转账。', '每月净存入2,000，全年就是24,000。'],
  'work.after': ['离开全职工作后的收入可减少早期从投资账户提款。', '只纳入有现实收入预期的兼职、顾问或生意，不算没有收入预期的爱好。', 'Alex离开主业后还做几年顾问工作。'],
  'work.amount': ['金额决定早期生活费中有多少不需要投资组合承担。', '填写扣所得税和经营费用前的预计全年毛收入。', '每月1,500顾问收入应填全年18,000。'],
  'work.period': ['开始和结束年龄决定具体哪些退休年份会收到这笔收入。', '填写你有把握持续工作的第一个和最后一个年龄。', '55岁到62岁的顾问收入形成7年过渡期。'],
  'assets.identify': ['不同账户的供款、增长和提款税务方式不同。', '看银行或券商账单上的账户标题；选择账户包装，不是基金或股票名称。', 'TFSA里的ETF应选择TFSA，不另建“ETF账户”。'],
  'account.tfsa.balance': ['TFSA提款免税，可灵活支付退休生活费。', '汇总所有TFSA当前市值；不要填未使用的供款额度。', '两个TFSA分别40,000和25,000，应合计填65,000。'],
  'account.rrsp.balance': ['RRSP/RRIF提款要纳税，余额会影响未来税额和提款顺序。', '汇总所有RRSP当前市值；夫妻合并计划只纳入双方实际拥有的账户。', '多张RRSP账单合计180,000，就填家庭总额180,000。'],
  'account.nonReg.balance': ['非注册投资可能每年产生应税分配，出售时还会产生资本增值。', '填写应税券商账户当前市值；排除日常付账用的活期现金。', '应税投资组合现在值90,000，就填90,000。'],
  'assets.cost': ['成本基础用于区分原始投入与出售时可能纳税的资本增值。', '从券商或报税记录查调整后成本基础，不要再填当前市值。', '现值100,000、买入成本80,000时，成本基础填80,000。'],
  'allocation.tfsa': ['这组比例决定未来每一元新增储蓄分别采用哪种账户税务方式。', '查看工资代扣和自动转账计划；TFSA、RRSP和非注册三个比例必须合计100%。', 'TFSA 30%加RRSP 50%，非注册账户应填20%。'],
  'fhsa.details': ['FHSA可用于合资格买房，并受年度供款限额约束。', '从FHSA账单和自动转账记录查当前市值与计划年供款。', '余额12,000、每年计划存8,000，要分别填写。'],
  'fhsa.open': ['FHSA有最长参与期限，所以开户时间会影响可继续使用多久。', '在金融机构记录中查首次开户日期，填写已经过去的完整年数。', '两年前首次开户，就填2。'],
  'locked.balance': ['锁定退休资金属于资产，但提前退休过渡期可能暂时不能使用。', '查看LIRA或锁定DC账户的最新账单市值。', '前雇主转出的85,000 LIRA填在这里，不填入普通RRSP。'],
  'locked.access': ['可提款年龄决定锁定资金何时能支付生活费；夫妻计划还要分清归属。', '查看养老金转移文件、LIRA账单及适用辖区规则。', '55岁可用的LIRA，在50岁退休后的前5年仍不可提款。'],
  'locked.contributions': ['你和雇主持续供款会改变退休前账户的增长。', '从工资单和单位计划账单查全年合计；个人供款不要超过总储蓄。', '个人6,000、雇主6,000要分开填写。'],
  'home.situation': ['租房、自有住房和计划买房会形成不同资产与现金流。', '选择最符合退休计划的路径，不只看今天住址。', '现在租房、五年后准备买房的人选择“计划买房”。'],
  'home.value': ['住房会增加净资产，但只有未来出售才会释放可用于生活的资金。', '参考近期同类成交或估价；只有确实准备卖时才填出售年龄。', '价值800,000但终身保留的住房不会产生售房现金。'],
  'home.mortgage': ['房贷会产生还款，并在卖房时减少可得到的净款。', '查看最新房贷账单是否仍有余额；不要再把同一笔列为其他贷款。', '已经还清的住房选择“没有”，即使过去曾有房贷。'],
  'mortgage.balance': ['未偿本金会减少住房净值，并且必须继续偿还。', '使用最新账单的本金余额，不是最初贷款金额。', '最初借500,000、现在剩310,000，应填310,000。'],
  'mortgage.payment': ['还款额和剩余年数决定住房贷款在哪些年份占用现金。', '把合同还款换算成全年金额，并填写剩余摊还年数。', '每月2,000应填每年24,000，例如还剩18年。'],
  'purchase.time': ['买房时间决定首付取出前，现有资产还能增长多久。', '按现实购房窗口填写预计交割时的年龄。', '现在40岁、五年后买房，购房年龄填45。'],
  'purchase.price': ['房价和首付决定要从投资取出多少现金，以及需要借多少。', '用目标价格区间和可用首付；这两个金额暂不包含成交费用。', '房价800,000、首付200,000，意味着约融资600,000。'],
  'purchase.loan': ['月供和年限决定计划贷款能否还清，以及未来现金负担。', '参考贷款预批或房贷计算器，并把月供换算为全年金额。', '每月3,500等于每年42,000，再填写所选摊还年限。'],
  'housing.other': ['投资房和其他贷款可能显著改变收入、净资产和所需生活费。', '这里只纳入尚未作为自住房房贷录入的项目。', '投资房房贷跟随投资房；车贷放在其他贷款。'],
  'rental.0.value': ['市值和成本基础决定房屋净值及出售时的应税增值。', '用近期估价，以及购买与资本改良记录计算的调整后成本。', '现值600,000、成本420,000，未实现增值是180,000。'],
  'rental.0.income': ['持有期间净租金形成应税收入；出售后这笔收入停止。', '填写扣除地税、管理和维修后的年租金，但不要扣房贷；只在确实计划卖时填年龄。', '年租金30,000减运营费10,000，净租金填20,000。'],
  'rental.0.mortgage': ['关联贷款会减少出售净款，还款也会影响出租现金流。', '使用这套投资房自己的贷款账单，不要在其他负债重复录入。', '只有以这套投资房相关的贷款才选择“有”。'],
  'rental.0.loan': ['余额和还款额共同决定投资房净值与年度现金需求。', '查最新本金余额，并把合同还款换算为全年金额。', '每月1,500应填每年18,000。'],
  'rental.0.term': ['剩余年数决定投资房贷款何时不再占用现金。', '填写剩余摊还年数，不是最初合同总年限。', '25年房贷现在还剩17年，就填17。'],
  'debt.0.type': ['贷款类型帮助说明负担，也防止房产贷款重复录入。', '从贷款合同或账单判断是房贷、车贷还是其他负债。', '信用额度应归为其他负债。'],
  'debt.0.balance': ['未偿负债会减少净资产，也可能延续到退休期。', '填写今天的本金余额，不包含未来利息。', '车贷还剩14,000本金，就填14,000。'],
  'debt.0.payment': ['还款额和剩余年数决定这笔贷款多久会增加退休支出。', '把强制还款换算为全年金额，并使用账单上的剩余期限。', '每月500、还剩3年，应填每年6,000和3年。'],
  'spending.method': ['已知总额和分项估算最终都会形成一个全年生活预算。', '根据现有记录和把握程度选择，不必为了少填几页选总额。', '有完整预算的人直接填总额；不确定的人按生活项目估算。'],
  'spending.total': ['这笔税后生活费决定投资组合每年必须提供多少提款。', '按今天价格填写，排除已单列贷款；把月支出换算为全年。', '每月4,000生活费等于每年48,000。'],
  'spending.homeFood': ['住房维护和饮食是退休后仍会持续的核心支出。', '查看近期全年消费；排除已在贷款页填写的房贷或其他还款。', '住房维护18,000、饮食9,000应分开填写。'],
  'spending.travelHealth': ['旅行和医疗在退休后常会变化，需要单独规划。', '结合近期支出、保险、牙科、药物和真实旅行计划估算。', '旅行6,000、医疗3,000都填全年金额。'],
  'spending.utilitiesTransport': ['停止通勤后，水电和交通仍是持续支出，但金额可能变化。', '查看账单、车辆和公交费用；只调整确实会在退休后改变的部分。', '通勤减少后，交通可从每年8,000调为5,000。'],
  'spending.funOther': ['娱乐和其他项目避免预算只覆盖最低生活必需。', '查看银行卡分类，并纳入不规则的年度项目；不要用过大的模糊缓冲。', '娱乐4,000加其他2,000可补完整份预算。'],
  'cpp.self': ['CPP/QPP金额和起领年龄决定应税政府收入何时开始。', '使用Service Canada或Retraite Québec的65岁年金额；没有官方金额时再用估算器。', '65岁每月1,000，65岁基准年金额应填12,000。'],
  'oas.self': ['OAS金额和起领年龄决定后期应税收入，也可能影响clawback。', '使用65岁官方估算，或按18岁后加拿大居住年数辅助估算。', '65岁每月725，应填每年8,700。'],
  'cpp.partner': ['伴侣的CPP/QPP是独立收入，有自己的金额和起领年龄。', '查看伴侣本人的Service Canada或Retraite Québec估算，不要复制你的金额。', '伴侣65岁基准年金额9,600，就在本页填9,600。'],
  'oas.partner': ['伴侣的OAS会单独计算，也可以在不同年龄开始。', '使用伴侣本人的居住经历或官方估算。', '伴侣67岁起领时，仍填写65岁基准金额，并把起领年龄填67。'],
  'pension.self': ['终身年金是收入；DC/LIRA是账户余额，两者不能用同一种方式填写。', '看账单是承诺定期金额，还是只显示一笔投资余额。', '承诺终身每月2,500是DB；只有200,000余额则是DC/LIRA。'],
  'pension.self.details': ['养老金金额和开始年龄决定单位收入能覆盖哪段退休期。', '使用养老金账单的退休估算，并把月金额换算为年金额。', '60岁起每月2,500，应填60岁起每年30,000。'],
  'pension.self.indexing': ['指数化保护购买力；过渡金通常只在65岁前临时发放。', '在计划手册查CPI、跟涨比例和bridge benefit金额。', '完全跟随通胀选“全部”；每年6,000过渡金另填。'],
  'pension.partner': ['伴侣的单位计划也要分清终身收入还是账户余额。', '查看伴侣自己的养老金账单，不要与本人的养老金合并。', '伴侣的锁定DC余额应走锁定账户路径，不填成DB收入。'],
  'pension.partner.details': ['伴侣养老金金额和开始年龄决定家庭提款何时下降。', '使用伴侣本人的退休估算，并把月金额换算为全年。', '65岁起每月1,500，应填每年18,000。'],
  'pension.partner.indexing': ['伴侣养老金的跟涨和过渡金会改变家庭长期购买力。', '查伴侣计划手册中的CPI调整和临时过渡金条款。', '金额固定不变时应选择“不跟涨”，即使起始金额较高。'],
  'intent.legacy': ['这个偏好决定结果是否重点比较剩余税后资产，不能根据有无孩子推断。', '按你对家人、朋友或公益的真实意愿选择，不需要查财务文件。', '没有孩子的人也可能希望把资产留给公益组织。'],
  'intent.spending': ['维持预算和探索理论支出上限回答的是两个不同问题。', '只选择希望看到的比较；查看上限不会自动改掉已填预算。', 'Alex维持50,000生活费，同时另看最多可能花多少。'],
  'intent.confirm': ['复述确认可防止系统把个人偏好偷偷转换成技术目标。', '仔细读摘要；如果没有准确表达你的意图，就返回修改。', '只有确认后，“维持支出并比较剩余”才映射为遗产比较。'],
  'invest.mix': ['投资配置决定预期收益和每年波动程度。', '按退休资产总体的股票、债券和现金比例选择，不要使用最近一年涨幅。', '60%股票、40%债券选择“平衡60/40”。'],
  'invest.fees': ['费用每年降低收益；通胀把今天价格与未来名义金额连接起来。', '从基金资料和顾问账单查MER；通胀使用长期假设，不照搬最近一年。', 'ETF费用0.2%、通胀2.1%都按百分比填写。'],
  'invest.tax': ['非注册分配会在退休前形成年度税耗，边际税率用于估算这项成本。', '查看基金分配历史，并从近期报税资料或税务计算器查边际税率。', '宽基ETF分配可约2%，工作期边际税率可能为35%。'],
  'invest.strategy': ['提款顺序会改变税额、福利clawback和以后剩余资产。', '选择希望采用的策略；结果页仍可比较其他方案。', '税档上限RRSP meltdown利用低收入年份，但不会一次清空RRSP。'],
  'assumptions.review': ['只有你知道投影依赖哪些估算后，才应该生成结果。', '核对收益、波动、费用、通胀和税务假设；不合适就返回前页修改。', '接受3%实际收益表示测试这个情景，不代表承诺未来一定发生。'],
}

// French copy stays page-specific as well; concise wording keeps the drawer readable.
const fr: Record<string, Copy> = Object.fromEntries(Object.entries(en).map(([id, copy]) => [id, copy]))
Object.assign(fr, {
  'family.people': ['La taille du ménage change l’impôt, les prestations et les revenus inclus.', 'Choisissez les personnes qui dépendront du même plan de retraite; aucun document requis.', 'Alex inclut son conjoint parce que les deux utiliseront le même plan.'],
  'family.ages': ['Les âges fixent la période d’épargne et alignent les prestations de chacun.', 'Utilisez les dates de naissance et l’âge actuel, pas l’âge à la retraite.', 'Alex a 40 ans et son conjoint 38 ans.'],
  'family.children': ['Les enfants de moins de 18 ans peuvent donner droit à l’Allocation canadienne pour enfants.', 'Utilisez l’âge actuel; excluez les enfants projetés ou adultes.', 'Un enfant de 7 ans est inclus; un enfant de 20 ans ne l’est pas.'],
  'family.province': ['La province détermine l’estimation d’impôt et certaines règles de prestations.', 'Utilisez la province où vous prévoyez être résident fiscal à la retraite.', 'Une personne qui prendra sa retraite à Vancouver choisit la C.-B.'],
  'time.work': ['Cet âge fixe les années d’épargne et le début du financement par le portefeuille.', 'Indiquez la fin du travail à temps plein; les prestations sont demandées séparément.', 'Alex cesse à 55 ans et demande le RPC à 65 ans.'],
  'time.horizon': ['Un horizon plus long teste davantage d’années de retraite.', 'Choisissez un âge prudent selon la longévité familiale; ce n’est pas une prédiction.', 'Alex teste le plan jusqu’à 95 ans.'],
  'saving.method': ['L’unité change seulement la saisie; le plan conserve un total annuel.', 'Choisissez l’unité utilisée dans votre budget ou vos relevés.', '2 000 $ par mois équivalent à 24 000 $ par année.'],
  'saving.amount': ['Les nouvelles cotisations font croître le portefeuille avant la retraite.', 'Additionnez les dépôts nets des 12 derniers mois; excluez gains et transferts.', '2 000 $ de dépôts mensuels donnent 24 000 $ par année.'],
  'work.after': ['Un revenu après le départ du travail principal réduit les retraits au début de la retraite.', 'Incluez seulement un emploi, des contrats ou une entreprise dont le revenu est plausible.', 'Alex prévoit quelques années de consultation après avoir quitté son emploi.'],
  'work.amount': ['Le montant indique quelle part du budget initial ne dépendra pas du portefeuille.', 'Inscrivez le revenu annuel brut prévu, avant impôt et dépenses d’entreprise.', '1 500 $ de consultation par mois équivalent à 18 000 $ par année.'],
  'work.period': ['Les âges de début et de fin placent ce revenu dans les bonnes années du plan.', 'Indiquez le premier et le dernier âge où ce travail devrait raisonnablement continuer.', 'Un revenu de 55 à 62 ans crée une transition de sept ans.'],
  'assets.identify': ['Le type de compte change l’impôt sur les cotisations, la croissance et les retraits.', 'Lisez le titre du compte sur le relevé; choisissez l’enveloppe, pas le fonds.', 'Un FNB détenu dans un CELI est saisi comme CELI.'],
  'account.tfsa.balance': ['Les retraits du CELI sont libres d’impôt et peuvent financer la retraite avec souplesse.', 'Additionnez la valeur actuelle de tous les CELI, pas les droits de cotisation inutilisés.', 'Deux CELI de 40 000 $ et 25 000 $ donnent un total de 65 000 $.'],
  'account.rrsp.balance': ['Les retraits REER/FERR sont imposables; le solde influence l’impôt futur et l’ordre des retraits.', 'Additionnez la valeur actuelle de tous les REER réellement détenus dans le ménage.', 'Plusieurs relevés totalisant 180 000 $ donnent un solde familial de 180 000 $.'],
  'account.nonReg.balance': ['Les placements non enregistrés peuvent produire des distributions et des gains imposables.', 'Inscrivez la valeur actuelle des comptes de courtage imposables, sans l’encaisse courante.', 'Un portefeuille imposable valant 90 000 $ est saisi à 90 000 $.'],
  'assets.cost': ['Le prix de base sépare le capital investi du gain qui pourrait être imposé à la vente.', 'Trouvez le prix de base rajusté dans les relevés ou dossiers fiscaux, pas la valeur actuelle.', 'Une valeur de 100 000 $ achetée 80 000 $ a un prix de base de 80 000 $.'],
  'allocation.tfsa': ['La répartition détermine le traitement fiscal de chaque dollar de nouvelle épargne future.', 'Utilisez les retenues salariales et virements prévus; CELI, REER et non enregistré doivent totaliser 100 %.', 'Avec 30 % au CELI et 50 % au REER, le compte non enregistré reçoit 20 %.'],
  'fhsa.details': ['Le CELIAPP peut financer un achat admissible et comporte des limites de cotisation annuelles.', 'Consultez le relevé CELIAPP et les virements prévus pour le solde et la cotisation annuelle.', 'Un solde de 12 000 $ et une cotisation de 8 000 $ sont deux montants distincts.'],
  'fhsa.open': ['La durée maximale du CELIAPP dépend de la date d’ouverture du premier compte.', 'Trouvez la date de première ouverture et inscrivez le nombre d’années complètes écoulées.', 'Si le premier CELIAPP a été ouvert il y a deux ans, inscrivez 2.'],
  'locked.balance': ['Les fonds immobilisés sont des actifs, mais peuvent être indisponibles au début de la retraite.', 'Utilisez la valeur actuelle du CRI ou du régime CD immobilisé sur le dernier relevé.', 'Un CRI de 85 000 $ provenant d’un ancien employeur est saisi ici, pas au REER.'],
  'locked.access': ['L’âge d’accès détermine quand ces fonds peuvent payer les dépenses et le propriétaire compte aussi.', 'Consultez les documents de transfert, le relevé CRI et les règles du territoire applicable.', 'Un CRI accessible à 55 ans ne finance pas les cinq premières années d’une retraite à 50 ans.'],
  'locked.contributions': ['Les cotisations de l’employé et de l’employeur font croître ce compte avant la retraite.', 'Trouvez les totaux annuels sur la paie et le relevé du régime; évitez les doubles comptes.', 'Inscrivez séparément 6 000 $ de l’employé et 6 000 $ de l’employeur.'],
  'home.situation': ['Location, propriété et achat futur créent des actifs et flux différents.', 'Choisissez le parcours du plan de retraite, pas seulement votre adresse actuelle.', 'Un locataire qui achètera dans cinq ans choisit « achat prévu ».'],
  'home.value': ['La résidence augmente la valeur nette, mais finance les dépenses seulement si elle est vendue.', 'Utilisez des ventes comparables ou une évaluation; indiquez un âge de vente seulement si elle est prévue.', 'Une maison de 800 000 $ conservée à vie ne crée pas de produit de vente.'],
  'home.mortgage': ['L’hypothèque exige des paiements et réduit le produit net lors d’une vente.', 'Vérifiez le dernier relevé; ne saisissez pas le même prêt comme autre dette.', 'Choisissez « non » si l’hypothèque est remboursée, même si la maison en avait une auparavant.'],
  'mortgage.balance': ['Le capital restant réduit la valeur nette de la maison et doit encore être remboursé.', 'Utilisez le solde de capital du dernier relevé, pas le montant emprunté au départ.', 'Un prêt initial de 500 000 $ dont il reste 310 000 $ est saisi à 310 000 $.'],
  'mortgage.payment': ['Le paiement et les années restantes placent le coût du logement dans les bonnes années.', 'Convertissez le paiement contractuel en montant annuel et inscrivez l’amortissement restant.', '2 000 $ par mois donnent 24 000 $ par année, avec par exemple 18 ans restants.'],
  'purchase.time': ['La date d’achat fixe le temps de croissance des actifs avant le retrait de la mise de fonds.', 'Inscrivez votre âge prévu à la clôture selon une fenêtre d’achat réaliste.', 'À 40 ans aujourd’hui avec un achat dans cinq ans, inscrivez 45.'],
  'purchase.price': ['Le prix et la mise de fonds déterminent le retrait initial et le financement requis.', 'Utilisez une fourchette cible réaliste et la mise de fonds disponible, hors frais de clôture.', 'Un prix de 800 000 $ et 200 000 $ comptant impliquent environ 600 000 $ de financement.'],
  'purchase.loan': ['Le paiement et la durée déterminent la charge future et la date de remboursement du prêt.', 'Utilisez une préapprobation ou un calculateur et convertissez le paiement mensuel en annuel.', '3 500 $ par mois donnent 42 000 $ par année, puis indiquez l’amortissement choisi.'],
  'housing.other': ['Les immeubles locatifs et autres prêts peuvent modifier fortement revenu, actif net et dépenses.', 'Incluez seulement ce qui n’a pas déjà été saisi comme hypothèque de résidence principale.', 'L’hypothèque locative suit l’immeuble; un prêt auto va dans les autres dettes.'],
  'rental.0.value': ['La valeur et le prix de base déterminent l’équité et le gain imposable à la vente.', 'Utilisez une évaluation récente et le coût rajusté incluant les améliorations en capital.', 'Une valeur de 600 000 $ et un coût de 420 000 $ donnent un gain latent de 180 000 $.'],
  'rental.0.income': ['Le loyer net est imposable pendant la détention et cesse après la vente.', 'Inscrivez le loyer annuel moins taxes, gestion et entretien, mais avant l’hypothèque.', '30 000 $ de loyers moins 10 000 $ de frais donnent 20 000 $ nets.'],
  'rental.0.mortgage': ['Le prêt lié réduit le produit de vente et ses paiements modifient les flux locatifs.', 'Utilisez le relevé du prêt de cet immeuble et ne le répétez pas dans les autres dettes.', 'Choisissez « oui » seulement pour un prêt rattaché à cet immeuble.'],
  'rental.0.loan': ['Le solde et le paiement déterminent ensemble l’équité et le besoin de trésorerie annuel.', 'Trouvez le capital restant et convertissez le paiement contractuel en montant annuel.', '1 500 $ par mois correspondent à 18 000 $ par année.'],
  'rental.0.term': ['Les années restantes indiquent quand ce prêt cessera de consommer de la trésorerie.', 'Inscrivez l’amortissement restant, pas la durée initiale du contrat.', 'Sur une hypothèque de 25 ans dont il reste 17 ans, inscrivez 17.'],
  'debt.0.type': ['Le type de prêt décrit l’obligation et évite de compter deux fois une hypothèque immobilière.', 'Consultez le contrat ou le relevé pour classer hypothèque, prêt auto ou autre dette.', 'Une marge de crédit se classe comme autre dette.'],
  'debt.0.balance': ['La dette restante réduit la valeur nette et peut continuer pendant la retraite.', 'Inscrivez le capital dû aujourd’hui, sans les intérêts futurs.', 'Un prêt auto dont le capital restant est 14 000 $ est saisi à 14 000 $.'],
  'debt.0.payment': ['Le paiement et les années restantes indiquent combien de temps la dette augmente les dépenses.', 'Convertissez le paiement obligatoire en annuel et utilisez la durée restante du relevé.', '500 $ par mois pendant trois ans donnent 6 000 $ par année et 3 ans.'],
  'spending.method': ['Un total connu ou une estimation par catégories produit le même budget annuel.', 'Choisissez selon vos dossiers et votre degré de confiance.', 'Sans budget détaillé, construisez le montant par catégories.'],
  'spending.total': ['Ce niveau de vie après impôt détermine les retraits nécessaires.', 'Utilisez les prix actuels et excluez les prêts saisis séparément.', '4 000 $ par mois deviennent 48 000 $ par année.'],
  'spending.homeFood': ['Le logement courant et l’alimentation restent des dépenses essentielles à la retraite.', 'Consultez une année récente et excluez les paiements de prêts déjà saisis.', 'Inscrivez séparément 18 000 $ de logement et 9 000 $ d’alimentation.'],
  'spending.travelHealth': ['Voyages et santé changent souvent à la retraite et méritent des estimations séparées.', 'Combinez dépenses récentes, assurance, soins dentaires, médicaments et projets de voyage.', '6 000 $ de voyages et 3 000 $ de santé sont des montants annuels.'],
  'spending.utilitiesTransport': ['Services publics et transport continuent après le travail, même si les déplacements changent.', 'Utilisez factures, véhicule et transport collectif, puis ajustez seulement les changements probables.', 'La fin des déplacements peut réduire le transport de 8 000 $ à 5 000 $ par année.'],
  'spending.funOther': ['Loisirs et autres dépenses empêchent le budget de couvrir seulement le strict nécessaire.', 'Consultez les catégories de carte et incluez les dépenses annuelles irrégulières.', '4 000 $ de loisirs et 2 000 $ d’autres dépenses complètent le budget.'],
  'cpp.self': ['Le montant RPC/RRQ et l’âge de demande fixent le début du revenu imposable.', 'Utilisez l’estimation annuelle à 65 ans de Service Canada ou Retraite Québec.', '1 000 $ par mois à 65 ans équivaut à 12 000 $ par année.'],
  'oas.self': ['Le montant et l’âge de la SV fixent le revenu futur et la récupération possible.', 'Utilisez l’estimation à 65 ans ou les années de résidence au Canada.', '725 $ par mois à 65 ans donnent 8 700 $ par année.'],
  'cpp.partner': ['Le RPC/RRQ du conjoint est un revenu distinct, avec son propre montant et âge de demande.', 'Utilisez l’estimation de Service Canada ou Retraite Québec du conjoint, pas la vôtre.', 'Si son montant de référence à 65 ans est 9 600 $, inscrivez 9 600 $.'],
  'oas.partner': ['La SV du conjoint est calculée séparément et peut commencer à un autre âge.', 'Utilisez ses années de résidence ou son estimation officielle personnelle.', 'Pour une demande à 67 ans, inscrivez quand même le montant de référence à 65 ans et l’âge 67.'],
  'pension.self': ['Une rente viagère est un revenu; un régime CD/CRI est un solde de compte.', 'Vérifiez si le relevé promet un paiement périodique ou montre seulement un solde.', '2 500 $ mensuels à vie est une PD; 200 000 $ est un compte CD/CRI.'],
  'pension.self.details': ['Le montant et l’âge de début placent le revenu de retraite d’employeur dans le plan.', 'Utilisez l’estimation du régime et convertissez tout montant mensuel en annuel.', '2 500 $ par mois dès 60 ans donnent 30 000 $ par année à partir de 60 ans.'],
  'pension.self.indexing': ['L’indexation protège le pouvoir d’achat; une rente de raccordement cesse souvent à 65 ans.', 'Consultez le livret du régime pour l’IPC, le taux d’indexation et la rente de raccordement.', 'Choisissez « pleine » si la rente suit l’inflation; inscrivez séparément un raccordement de 6 000 $.'],
  'pension.partner': ['Le régime du conjoint doit aussi être classé comme rente viagère ou solde de compte.', 'Consultez son propre relevé et ne combinez pas sa rente avec la vôtre.', 'Son solde CD immobilisé suit le parcours CRI, pas celui d’une rente PD.'],
  'pension.partner.details': ['Le montant et l’âge de début de la rente du conjoint réduisent les retraits du ménage.', 'Utilisez son estimation de retraite et convertissez le montant mensuel en annuel.', '1 500 $ par mois dès 65 ans donnent 18 000 $ par année.'],
  'pension.partner.indexing': ['L’indexation et le raccordement du conjoint modifient le pouvoir d’achat familial à long terme.', 'Consultez son livret pour les ajustements à l’IPC et les prestations temporaires.', 'Choisissez « fixe » si le montant ne monte jamais, même si la rente initiale est élevée.'],
  'intent.legacy': ['Cette préférence oriente la comparaison de l’actif restant; elle ne vient pas du nombre d’enfants.', 'Choisissez selon vos intentions envers proches ou organismes.', 'Une personne sans enfant peut vouloir léguer à un organisme.'],
  'intent.spending': ['Maintenir le budget et explorer un plafond répondent à deux questions différentes.', 'Choisir de voir le plafond ne modifie pas votre budget.', 'Alex garde 50 000 $ et examine séparément le maximum possible.'],
  'intent.confirm': ['La confirmation empêche de transformer silencieusement une préférence en objectif technique.', 'Relisez le résumé et revenez en arrière s’il ne reflète pas votre intention.', 'La comparaison successorale n’est appliquée qu’après confirmation.'],
  'invest.mix': ['La répartition détermine le rendement attendu et l’incertitude annuelle.', 'Utilisez la part globale actions-obligations-encaisse, pas le rendement récent.', '60 % actions et 40 % obligations correspond à Équilibré 60/40.'],
  'invest.fees': ['Les frais réduisent le rendement; l’inflation relie les prix actuels aux montants futurs.', 'Trouvez le RFG dans l’aperçu du fonds et utilisez une inflation à long terme.', 'Des frais de 0,2 % et une inflation de 2,1 % sont des pourcentages.'],
  'invest.tax': ['Les distributions imposables créent une ponction fiscale annuelle avant la retraite.', 'Consultez l’historique des distributions et votre taux marginal récent.', 'Un FNB peut distribuer 2 % avec un taux marginal de 35 %.'],
  'invest.strategy': ['L’ordre des retraits change l’impôt, les récupérations et l’actif restant.', 'Choisissez la stratégie à appliquer; les résultats compareront les autres.', 'Une fonte REER plafonnée utilise les années à faible revenu.'],
  'assumptions.review': ['Le résultat ne doit être généré qu’après reconnaissance de ses hypothèses.', 'Vérifiez rendement, volatilité, frais, inflation et fiscalité.', 'Accepter 3 % réel teste un scénario; ce n’est pas une promesse.'],
})

const languages: Record<GuidanceLanguage, Record<string, Copy>> = { en, fr, zh }

export function guidanceForPage(pageId: string, language: string): PageGuidance {
  const lang: GuidanceLanguage = language.startsWith('zh') ? 'zh' : language.startsWith('fr') ? 'fr' : 'en'
  const copy = languages[lang][pageId] ?? languages.en[pageId]
  if (!copy) throw new Error(`Missing page guidance for ${pageId}`)
  return { why: copy[0], find: copy[1], example: copy[2] }
}

export function hasLocalizedGuidance(pageId: string, language: GuidanceLanguage): boolean {
  return Boolean(languages[language][pageId])
}
